services:
    sonata.admin.single_event:
        class: App\AdminBundle\Admin\Event\Type\SingleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: event, label: "Évènement simple" }
        arguments:
            - ~
            - App\EventBundle\Entity\Type\Single
            - ~

    sonata.admin.event:
        class: App\AdminBundle\Admin\Event\AbstractEventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: event, label: "Event", show_in_dashboard: false }
        arguments:
            - ~
            - App\EventBundle\Entity\Event
            - ~

    sonata.admin.cylic_event:
        class: App\AdminBundle\Admin\Event\Type\CyclicAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: event, label: "Évènements cycliques", show_in_dashboard: false }
        arguments:
            - ~
            - App\EventBundle\Entity\Type\Cyclic
            - ~
