services:
    # Sports
    sonata.admin.sports:
        class: App\AdminBundle\Admin\Sport\SportAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sport, label: "Sports" }
        arguments:
            - ~
            - App\SportBundle\Entity\Sport
            - AppAdminBundle:SportAdmin

    # Categories
    sonata.admin.categories:
        class: App\AdminBundle\Admin\Sport\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sport, label: "Catégories" }
        arguments:
            - ~
            - App\SportBundle\Entity\Category
            - AppAdminBundle:CategoryAdmin

    # Tags
    sonata.admin.tags:
        class: App\AdminBundle\Admin\Sport\TagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: sport, label: "Tags" }
        arguments:
            - ~
            - App\SportBundle\Entity\Tag
            - AppAdminBundle:TagAdmin

    # User -> Sport
    app_admin.admin.sport_user:
        class: App\AdminBundle\Admin\Sport\SportUserAdmin
        arguments:
          - ~
          - App\SportBundle\Entity\SportUser
          - AppAdminBundle:SportUserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: SportUser }
