services:
# Base User
    sonata.user.admin.user:
        class: "%sonata.user.admin.user.class%"
        tags:
            - { name: sonata.admin, manager_type: orm, group: %sonata.user.admin.groupname%, label: "Tous les utilisateurs", label_catalogue: %sonata.user.admin.label_catalogue%", icon: "%sonata.user.admin.groupicon%"}
        arguments:
            - ~
            - %sonata.user.admin.user.entity%
            - %sonata.user.admin.user.controller%
        calls:
            - [setUserManager, ["@fos_user.user_manager"]]
            - [setTranslationDomain, ["%sonata.user.admin.user.translation_domain%"]]

# User types
    # Coachs
    sonata.admin.users_coachs:
        class: App\AdminBundle\Admin\User\Type\CoachAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: "Coachs" }
        arguments:
            - ~
            - App\UserBundle\Entity\User
            - AppAdminBundle:CoachAdmin
        calls:
            - [setUserManager, ["@fos_user.user_manager"]]
            - [setRealLabel, ['Coach']]
            - [setTranslationDomain, ["%sonata.user.admin.user.translation_domain%"]]


    # Providers
    sonata.admin.users_providers:
        class: App\AdminBundle\Admin\User\Type\ProviderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: "Providers" }
        arguments:
            - ~
            - App\UserBundle\Entity\User
            - AppAdminBundle:ProviderAdmin
        calls:
            - [setUserManager, ['@fos_user.user_manager']]
            - [setRealLabel, ['Provider']]
            - [setTranslationDomain, ["%sonata.user.admin.user.translation_domain%"]]

    # Sportroopers
    sonata.admin.users_sportroopers:
        class: App\AdminBundle\Admin\User\Type\SportrooperAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: "Sportroopers" }
        arguments:
            - ~
            - App\UserBundle\Entity\User
            - AppAdminBundle:SportrooperAdmin
        calls:
            - [setUserManager, ['@fos_user.user_manager']]
            - [setRealLabel, ['Sportrooper']]
            - [setTranslationDomain, ["%sonata.user.admin.user.translation_domain%"]]


    # Administrators
    sonata.admin.users_admins:
        class: App\AdminBundle\Admin\User\Type\AdminsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: "Administrateurs" }
        arguments:
            - ~
            - App\UserBundle\Entity\User
            - AppAdminBundle:AdminsAdmin
        calls:
            - [setUserManager, ['@fos_user.user_manager']]
            - [setRealLabel, ['Administrateur']]
            - [setTranslationDomain, ["%sonata.user.admin.user.translation_domain%"]]


# User associations
     # User -> CoachInformation
    sonata.admin.coach_information:
        class: App\AdminBundle\Admin\User\Information\CoachInformationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Utilisateurs", label: "Coach informations" , show_in_dashboard: false }
        arguments:
            - ~
            - App\UserBundle\Entity\Information\CoachInformation
            - AppAdminBundle:CoachInformationAdmin

    # User -> ProviderInformation
    sonata.admin.provider_information:
        class: App\AdminBundle\Admin\User\Information\ProviderInformationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Utilisateurs", label: "Provider informations" , show_in_dashboard: false }
        arguments:
            - ~
            - App\UserBundle\Entity\Information\ProviderInformation
            - AppAdminBundle:ProviderInformationAdmin

    # CoachInformation -> CoachDocument
    sonata.admin.coach_document:
        class: App\AdminBundle\Admin\User\Information\CoachDocumentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Utilisateurs", label: "Coach documents" , show_in_dashboard: false }
        arguments:
            - ~
            - App\UserBundle\Entity\Information\CoachDocument
            - AppAdminBundle:CoachDocumentAdmin
