parameters:
    api.event.jwt_response_listener.class: App\UserBundle\EventListener\JwtResponseListener
    api.kernel.listener.exception_listener.class: App\UserBundle\EventListener\ExceptionResponseListener

services:
    api.event.jwt_response_listener:
        class: %api.event.jwt_response_listener.class%
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    api.kernel.listener.exception_listener:
        class: %api.kernel.listener.exception_listener.class%
        tags:
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelResponse}
