# API
api:
  prefix: /v1/
  resource: "routing_api.yml"
  requirements:
      _format: json|xml

# Demo
app_demo:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    demo.html.twig

# API documentation
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc/v1
