app_security:
    resource: "@AppUserBundle/Resources/config/routing.yml"
    prefix:   /
    requirements:
        _format: json

app_refresh_token:
    path:     /refresh_token
    methods: POST
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

sports_resource:
    resource: App\SportBundle\Controller\SportsController
