# Security related routing (users and sessions management)
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

api_security:
    resource: "@AppUserBundle/Resources/config/routing.yml"
    prefix:   /
    requirements:
        _format: json

sports:
    resource: "@AppSportBundle/Resources/config/routing.yml"

events:
    resource: "@AppEventBundle/Resources/config/routing.yml"
