app_security:
    resource: "@AppUserBundle/Resources/config/routing.yml"
    prefix:   /
    requirements:
        _format: json

app_refresh_token:
    path:     /refresh_token
    methods: POST
    defaults: { _controller: AppUserBundle:Security:refreshToken }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
