app_api:
  host: "api.%domain%"
  prefix: /v1/
  resource: "routing_api.yml"

app_admin:
    host: "%domain%"
    prefix: /
    resource: "routing_admin.yml"

app_api_demo:
    host: "api.%domain%"
    path: /
    defaults: { _controller: AppSportBundle:Default:index }

# Eventual FOSOAuthServerBundle routing
# fos_oauth_server_token:
#     resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
#
# fos_oauth_server_authorize:
#     resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
#
#
app_oauth_login:
    path: /oauth/login
    defaults: { _controller: AppSportBundle:Default:oauthLogin }

app_secured:
    path:  /secured/test
    defaults: { _controller: AppSportBundle:Default:secured }

# hwi_oauth_redirect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#     prefix:   /oauth/connect
#
# hwi_oauth_login:
#   resource: "@AppUserBundle/Resources/config/routing/login.yml"
#   prefix: /oauth

facebook_login:
    pattern: /oauth/check-facebook

hwi_oauth_logout:
    path: /oauth/logout
