# API
api:
  prefix: /v1/
  resource: "routing_api.yml"
  requirements:
      _format: json|xml

# API demo
app_demo:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    demo.html.twig

# Security related routing (users and sessions management)
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    
# API documentation
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc/v1
