# Security related routing (users and sessions management)
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

api_security:
    resource: "@AppUserBundle/Resources/config/routing.yml"
    prefix:   /
    requirements:
        _format: json

api_refresh_token:
    path:     /refresh_token
    methods: POST
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
    
sports:
    resource: "@AppSportBundle/Resources/config/routing.yml"
