# Security related routing (users and sessions management)
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

api_security:
    resource: "@AppUserBundle/Resources/config/routing.yml"
    prefix:   /
    requirements:
        _format: json

api_refresh_token:
    path:     /refresh_token
    methods: POST
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }



# One Controller per collection
# Here the SportsController containing all Resources related to Sport (/v1/sports collection)
sports_resource:
    # Inside this controller, routes are registered manually using the @Rest annotation (@Rest\Get|Post|Put|..)
    # @see http://symfony.com/doc/current/bundles/FOSRestBundle/7-manual-route-definition.html
    resource: App\SportBundle\Controller\SportsController

categories_resource:
    resource: App\SportBundle\Controller\CategoriesController

sports:
    resource: "@AppSportBundle/Resources/config/routing.yml"
