app_api:
  prefix: /v1/
  resource: "routing_api.yml"
  requirements:
      _format: json

app_admin:
    host: "%domain%"
    prefix: /
    resource: "routing_admin.yml"

app_demo:
    host: "api.%domain%"
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    AppUserBundle:Default:list.html.twig

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc/v1
