admin_home:
    resource: "@AppAdminBundle/Resources/config/routing.yml"
    prefix: /

admin_security:
    resource: "@AppAdminBundle/Resources/config/security.yml"
    prefix: /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
