app_api:
  host: "api.%domain%"
  prefix: /v1/
  resource: "routing_api.yml"
  requirements:
      _format: json

app_admin:
    host: "%domain%"
    prefix: /
    resource: "routing_admin.yml"

app_demo:
    host: "api.%domain%"
    path: /
    defaults: { _controller: AppUserBundle:Security:demo }
