parameters:
  # api.kernel.listener.exception_listener.class: App\Util\EventListener\ExceptionResponseListener
    app.doctrine.abstract_repository_factory.class: App\Util\Doctrine\Repository\EnhancedRepositoryFactory

services:

  # api.kernel.listener.exception_listener:
  #     class: %api.kernel.listener.exception_listener.class%
  #     tags:
  #         - { name: kernel.event_listener, event: kernel.exception, method: onKernelResponse }

    app.doctrine.repository.factory:
        class: %app.doctrine.abstract_repository_factory.class%
        arguments:
            - []
            - '@service_container'
            - '@app.doctrine.repository.factory.default'

    app.doctrine.repository.factory.default:
        class: Doctrine\ORM\Repository\DefaultRepositoryFactory
