services:
  
    # EnhancedRepository Factory
    app.doctrine.repository.factory:
        class: Util\Doctrine\Repository\EnhancedRepositoryFactory
        arguments:
            - []
            - '@service_container'
            - '@app.doctrine.repository.factory.default'

    # EnhancedRepository
    app.doctrine.repository.factory.default:
        class: Doctrine\ORM\Repository\DefaultRepositoryFactory
