# Default configuration for "SonataAdminBundle"
sonata_admin:
    security:
        handler:              sonata.admin.security.handler.noop
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        admin_permissions:
            # Defaults:
            - CREATE
            - LIST
            - DELETE
            - UNDELETE
            - EXPORT
            - OPERATOR
            - MASTER
        object_permissions:
            # Defaults:
            - VIEW
            - EDIT
            - DELETE
            - UNDELETE
            - OPERATOR
            - MASTER
            - OWNER
        acl_user_manager:     ~         # Name of the user manager service used to retrieve ACL users
    title:                Sonata Admin
    title_logo:           bundles/sonataadmin/logo_title.png
    options:
        html5_validate:                         true      # use html5 validation
        confirm_exit:                           true      # enabled confirmation when quitting with unsaved changes
        use_select2:                            true      # enable select2
        use_icheck:                             true      # enable iCheck
        pager_links:                            5         # pager max links to display
        dropdown_number_groups_per_colums:      2         # max items per column in dropdown menu (add button in top nav)
        title_mode:           'single_image'              # 'both', 'single_text' or 'single_image'
    dashboard:
        groups:
            user:
                label: "Utilisateurs"
                items:
                    - sonata.user.admin.group
                    - sonata.user.admin.user
                    - sonata.admin.users_admins
                    - sonata.admin.users_sportroopers
                    - sonata.admin.users_coachs
                    - sonata.admin.users_providers
            sport:
                label: "Sport"

        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
    templates:
        layout:                    AppAdminBundle:Default:standard_layout.html.twig
        short_object_description:  SonataAdminBundle:Helper:short-object-description.html.twig
        user_block:                AppAdminBundle:Block:user_block.html.twig

    admin_services:
        # Prototype
        id:
            model_manager:        ~
            form_contractor:      ~
            show_builder:         ~
            list_builder:         ~
            datagrid_builder:     ~
            translator:           ~
            configuration_pool:   ~
            validator:            ~
            security_handler:     ~
            label:                ~

    extensions:
        id:
            admins:               []
            excludes:             []
            implements:           []
            extends:              []
            instanceof:           []

    persist_filters:      false     # set to true to persist filter settings per admin module in the user's session
