# One Controller per collection
# Here the SportsController containing all Resources related to Sport (/v1/sports collection)
sports_collection:
    # Inside this controller, routes are registered manually using the @Rest annotation (@Rest\Get|Post|Put|..)
    # @see http://symfony.com/doc/current/bundles/FOSRestBundle/7-manual-route-definition.html
    resource: App\SportBundle\Controller\SportsController

categories_collection:
    resource: App\SportBundle\Controller\CategoriesController

tags_collection:
    resource: App\SportBundle\Controller\TagsController
