parameters:
    admin.patched_model_type.class: App\AdminBundle\Form\Type\PatchedModelType
    admin.sports.class: App\AdminBundle\Admin\Sport\SportAdmin
    admin.categories.class: App\AdminBundle\Admin\Sport\CategoryAdmin
    admin.tags.class: App\AdminBundle\Admin\Sport\TagAdmin

services:

    sonata.admin.sports:
        class: "%admin.sports.class%"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Sports", label: "Sports" }
        arguments:
            - ~
            - App\SportBundle\Entity\Sport # The corresponding entity 
            - AppAdminBundle:SportAdmin # The Admin Class

    sonata.admin.categories:
        class: "%admin.categories.class%"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Sports", label: "Catégories" }
        arguments:
            - ~
            - App\SportBundle\Entity\Category
            - AppAdminBundle:CategoryAdmin

    sonata.admin.tags:
        class: "%admin.tags.class%"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Sports", label: "Tags" }
        arguments:
            - ~
            - App\SportBundle\Entity\Tag
            - AppAdminBundle:TagAdmin
