parameters:
    admin.patched_model_type.class: App\AdminBundle\Form\Type\PatchedModelType
    admin.sports.class: App\AdminBundle\Admin\Sport\SportAdmin
    admin.categories.class: App\AdminBundle\Admin\Sport\CategoryAdmin
    admin.tags.class: App\AdminBundle\Admin\Sport\TagAdmin
    admin.coachs.class: App\AdminBundle\Admin\User\CoachAdmin

services:

    sonata.admin.sports:
        class: "%admin.sports.class%"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Sports", label: "Sports" }
        arguments:
            - ~
            - App\SportBundle\Entity\Sport
            - AppAdminBundle:SportAdmin

    sonata.admin.categories:
        class: "%admin.categories.class%"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Sports", label: "Catégories" }
        arguments:
            - ~
            - App\SportBundle\Entity\Category
            - AppAdminBundle:CategoryAdmin

    sonata.admin.tags:
        class: "%admin.tags.class%"
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Sports", label: "Tags" }
        arguments:
            - ~
            - App\SportBundle\Entity\Tag
            - AppAdminBundle:TagAdmin

    # @Thuy First admin class for you as example, I know it's a lot of search to know where files are located and how do it.
    # Also, take a look at this declaration, it is how you create a new "Admin section" in our back-office.
    # For it's example, it is the CoachAdmin class.
    # ! You have to create the CoachInformation entity like I say in the ticket, I havn't done it. !
    # If you have any doubt / need of resource or example, do not hesitate to ask me.
    # Thank's for your job
    sonata.admin.users_coachs:
        class: "%admin.coachs.class%" # Previously declared at top (parameters)
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Coachs", label: "Coachs" } # Some parameters of sonata
        arguments:
            - ~
            - App\UserBundle\Entity\User # The entity used, main entity but custom fields from the relation with CoachInformation.
            - AppAdminBundle:CoachAdmin #  The admin class alias, mandatory too.
