parameters:
    admin.patched_model_type.class: App\AdminBundle\Form\Type\PatchedModelType
    admin.sports.class: App\AdminBundle\Admin\Sport\SportAdmin
    admin.categories.class: App\AdminBundle\Admin\Sport\CategoryAdmin
    admin.tags.class: App\AdminBundle\Admin\Sport\TagAdmin
    admin.coach.class: App\AdminBundle\Admin\User\Type\CoachAdmin
    admin.provider.class: App\AdminBundle\Admin\User\Type\ProviderAdmin
    admin.sportrooper.class: App\AdminBundle\Admin\User\Type\SportrooperAdmin
    admin.admin.class: App\AdminBundle\Admin\User\Type\AdminsAdmin

services:

    sonata.admin.sports:
        class: "%admin.sports.class%"
        tags:
            - { name: sonata.admin, manager_type: orm, group: sport, label: "Sports" }
        arguments:
            - ~
            - App\SportBundle\Entity\Sport # The corresponding entity
            - AppAdminBundle:SportAdmin # The Admin Class

    sonata.admin.categories:
        class: "%admin.categories.class%"
        tags:
            - { name: sonata.admin, manager_type: orm, group: sport, label: "Catégories" }
        arguments:
            - ~
            - App\SportBundle\Entity\Category
            - AppAdminBundle:CategoryAdmin

    sonata.admin.tags:
        class: "%admin.tags.class%"
        tags:
            - { name: sonata.admin, manager_type: orm, group: sport, label: "Tags" }
        arguments:
            - ~
            - App\SportBundle\Entity\Tag
            - AppAdminBundle:TagAdmin

    sonata.admin.users_coachs:
        class: "%admin.coach.class%"
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: "Coachs" }
        arguments:
            - ~
            - App\UserBundle\Entity\User
            - AppAdminBundle:CoachAdmin
        calls:
            - [setUserManager, ["@fos_user.user_manager"]]

    sonata.admin.users_providers:
        class: "%admin.provider.class%"
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: "Providers" }
        arguments:
            - ~
            - App\UserBundle\Entity\User
            - AppAdminBundle:ProviderAdmin
        calls:
            - [setUserManager, ['@fos_user.user_manager']]

    sonata.admin.users_sportroopers:
        class: "%admin.sportrooper.class%"
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: "Sportroopers" }
        arguments:
            - ~
            - App\UserBundle\Entity\User
            - AppAdminBundle:SportrooperAdmin
        calls:
            - [setUserManager, ['@fos_user.user_manager']]

    sonata.admin.users_admins:
        class: "%admin.admin.class%"
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: "Admins" }
        arguments:
            - ~
            - App\UserBundle\Entity\User
            - AppAdminBundle:AdminsAdmin
        calls:
            - [setUserManager, ['@fos_user.user_manager']]

    sonata.admin.coach_information:
        class: App\AdminBundle\Admin\User\Information\CoachInformationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Utilisateurs", label: "Coach informations" , show_in_dashboard: false }
        arguments:
            - ~
            - App\UserBundle\Entity\Information\CoachInformation
            - AppAdminBundle:CoachInformationAdmin
            -

    sonata.admin.provider_information:
        class: App\AdminBundle\Admin\User\Information\ProviderInformationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Utilisateurs", label: "Provider informations" , show_in_dashboard: false }
        arguments:
            - ~
            - App\UserBundle\Entity\Information\ProviderInformation
            - AppAdminBundle:ProviderInformationAdmin
