services:
    sonata.admin.sports:
        class: App\AdminBundle\Admin\SportAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Sports", label: "Sports" }
        arguments:
            - ~
            - App\SportBundle\Entity\Sport
            - AppAdminBundle:SportAdmin

    sonata.admin.categories:
        class: App\AdminBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Catégories", label: "Catégories" }
        arguments:
            - ~
            - App\SportBundle\Entity\Category
            - AppAdminBundle:CategoryAdmin
