services:
    sonata.admin.sport:
        class: App\AdminBundle\Admin\SportAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Sports", label: "Liste des sports" }
        arguments:
            - ~
            - App\SportBundle\Entity\Sport
            - AppAdminBundle:SportAdmin
